# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1162, 804)
        self.com_open = QtWidgets.QPushButton(Form)
        self.com_open.setGeometry(QtCore.QRect(900, 80, 220, 80))
        self.com_open.setObjectName("pushButton")
        self.uart_name = QtWidgets.QComboBox(Form)
        self.uart_name.setGeometry(QtCore.QRect(900, 190, 220, 60))
        self.uart_name.setObjectName("comboBox")
        self.log = QtWidgets.QTextBrowser(Form)
        self.log.setGeometry(QtCore.QRect(20, 20, 541, 751))
        self.log.setObjectName("textBrowser")
        self.clear_log = QtWidgets.QPushButton(Form)
        self.clear_log.setGeometry(QtCore.QRect(580, 730, 91, 41))
        self.clear_log.setObjectName("pushButton_2")
        self.btn_ask_vol = QtWidgets.QPushButton(Form)
        self.btn_ask_vol.setGeometry(QtCore.QRect(600, 70, 120, 40))
        self.btn_ask_vol.setObjectName("pushButton_3")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.com_open.setText(_translate("Form", "打开串口"))
        self.clear_log.setText(_translate("Form", "Clear"))
        self.btn_ask_vol.setText(_translate("Form", "查询电压"))

